services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: tasks_db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"   # Limitar el uso de CPU
          memory: "256M" # Limitar el uso de memoria
    # restart: on-demand # Solo reinicia si se llama
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - '5432:5432'
